name: rfod-cs5344
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter
  - ipykernel
  - tqdm
  - pip
  - pip:
    - pyod>=1.0.0
